### ISSUE TITLE
PlaceholderAPI Support

### ISSUE THREAD

**Issue by iplusplus42** [AceKiron-Community/pronounmc#24]
## Is your feature request related to a problem? Please describe.
I'd like to be able to have pronouns preceding/succeeding one's username, but I see no way to do that currently.

## Describe the solution you'd like
I propose adding one placeholder for each pronoun type, something like the following:
- %pronounmc_objective%
- %pronounmc_subjective%
- %pronounmc_reflexive%
- %pronounmc_posessive%
- %pronounmc_posessive_adj%

## Describe alternatives you've considered
I'm honestly not sure what any alternatives would be, but I'm open to suggestions.

**Comment by EnbyAce** [comment]
What version of the plugin are you using?
We actually had PlaceholderAPI implemented in an earlier version, but this has been removed in v2.0 as it just isn't that simple anymore.

At first we had `%pronounmc_pronouns%` return somebody's pronouns, like `He/him`, `He/they`, `They/it`, `Unspecified`, `Any`, and `Username`, but in the later versions each set of pronouns can have one of the following statuses for each player:

- Ask
- Yes
- Jokingly
- Only if we are close
- Okay
- Nope

However, if you are good with PlaceholderAPI and know a solution, feel free to contribute to the code.

**Comment by EnbyAce** [comment]
Stale issue, so I'm closing this.
