### ISSUE TITLE
Add a licence

### ISSUE THREAD

**Issue by Purrrpley** [AceKiron-Community/pronounmc#4]
Currently, this project has no license associated with it [meaning it's under exclusive copyright to you](https://choosealicense.com/no-permission/) and no one else is allowed to use, copy, or modify it. That might be what you want, though probably isn't if you've put it on GitHub and made the source code available, so you should [add a license](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) to allow others to do stuff with the code here other than look at it. If you don't know what license to add, https://choosealicense.com can help.

(note: I am not a lawyer and this is not legal advice, however is correct to my knowledge. I noticed some typos and stuff I wanted to fix when looking though the code here but then realised I legally couldn't because there's no license letting me ;-;)

**Comment by EnbyAce** [comment]
In that case, MIT license has been added in 14198dbd5a546e4e5e9fe6dfd77d83a3561eab25

**Comment by EnbyAce** [comment]
> @AceKiron don wanna necro but mit might not be compatible with GPL

GPL? I don't think I'm using anything that's using GPL.

**Comment by KaspianDev** [comment]
> > @AceKiron don wanna necro but mit might not be compatible with GPL
> 
> GPL? I don't think I'm using anything that's using GPL.

Bukkit is under GPLv3 (and so is spigot)

**Comment by EnbyAce** [comment]
> > > @AceKiron don wanna necro but mit might not be compatible with GPL
> > 
> > 
> > GPL? I don't think I'm using anything that's using GPL.
> 
> Bukkit is under GPLv3 (and so is spigot)

I did some quick research online and this is what I think is the case:
- You must use the GPLv3 license if you're modifying Bukkit, Spigot etc.
- You may choose your own license in other cases

**Comment by KaspianDev** [comment]
> > > > @AceKiron don wanna necro but mit might not be compatible with GPL
> > > 
> > > 
> > > GPL? I don't think I'm using anything that's using GPL.
> > 
> > 
> > Bukkit is under GPLv3 (and so is spigot)
> 
> I did some quick research online and this is what I think is the case:
> 
>     * You must use the GPLv3 license if you're modifying Bukkit, Spigot etc.
> 
>     * You may choose your own license in other cases

I don't know where you found that, but it's not true. (send me the source please)
The only exception where you may be able exempt from gpl infection is using library under LGPL, which spigot isnt.
In short: you are extending JavaPlugin which is a Bukkit class.

You'd have to check if relicensing GPL to MIT is allowed in that case.

**Comment by Purrrpley** [comment]
I'm not a lawyer and so this is not legal advice, but I think this is allowed, actually.

From [gnu.org](https://www.gnu.org/licenses/gpl-faq.en.html#GPLAndPlugins):
> Please see this question [for determining when plug-ins and a main program are considered a single combined program and when they are considered separate works](https://www.gnu.org/licenses/gpl-faq.en.html#GPLPlugins).
>
> If the main program and the plugins are a single combined program then this means you must license the plug-in under the GPL or a GPL-compatible free software license and distribute it with source code in a GPL-compliant way. A main program that is separate from its plug-ins makes no requirements for the plug-ins.

[MIT is a GPL-compatible free software license](https://www.gnu.org/licenses/license-list.html#X11License).

I'm not entirely sure what it means by distributing it in a GPL-compliant way though, or if there's even an actual difference between licensing this under MIT or licensing it under the GPL if it's going to be GPL-compliant anyway.

**Comment by EnbyAce** [comment]
MIT does indeed seem compatible with GPL. If it turns out it isn't, please create a new issue.
