### ISSUE TITLE
Hovering over someone's username should show their pronouns in hover text

### ISSUE THREAD

**Issue by Purrrpley** [AceKiron-Community/pronounmc#7]
## Is your feature request related to a problem? Please describe.
It can be a little annoying to type `/getpronouns <username>` every time you want to know the pronouns of someone

## Describe the solution you'd like
Some hover text over people's usernames that tells you what their pronouns are, so it's quicker and easier to check

## Describe alternatives you've considered
Could just deal with it being slightly time-consuming and remember things, but this would be more convenient so I suggested it :p Also could maybe only happen for the player message prefix thing instead of every single time their username is said in chat

## Additional context
Not sure how compatible this would be with other plugins that modify chat :/ Also here's an example showing what I mean done with a `/tellraw` command:
![image](https://user-images.githubusercontent.com/63091454/151936621-7ff34fe6-7b38-48eb-96b1-1490f0c7d748.png)

**Comment by EnbyAce** [comment]
Interesting idea, but yeah, sounds amazingly hard to implement, mainly because of other chat modifying plugins :/

**Comment by EnbyAce** [comment]
Nope, I'd need the maintainer(s) of the AutHelper plugin to either implement this themselves or have them share the source code of the latest version with me so I can implement it for them. Same applies to maintainers of other plugins.

**Comment by Just-Leah** [comment]
Perhaps integration with placeholder api would be useful because then the pronouns of a certain player could be inserted anywhere easily

**Comment by EnbyAce** [comment]
@Stonewall0210 that sounds interesting

**Comment by EnbyAce** [comment]
I don't have access to AutHelper (the plugin AC uses for chat)'s source code and I even heard it would be rewritten from scratch, so I could not implement this feature yet.
I have however made a plugin that adds the pronouns of the sender in the chat message, you can find the code on https://github.com/AceKiron/pronounmc/blob/chat/src/main/java/io/github/acekiron/pronounmcchat/PronounmcChat.java.

**Comment by Just-Leah** [comment]
I read through the placeholder api wiki a bit, it seems relatively simple, especially with the way things read set up.

From my understanding placeholder api runs a set method whenever a placeholder is referenced, and whatever is returned from that is used in the placeholder (returning null makes it fail and not change the placeholder).
If I’m not mistaken this plug-in handles pronouns in a similar method, using a method in it’s own api to return the pronouns of a specific player in string form.
So in theory it should work.

if you want I can have a go at trying to add this, it seems simple enough to me at least. It really depends on if I get a sudden burst of motivation again like yesterday was like.

*btw here’s the [placeholder api wiki](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki)*

**Comment by EnbyAce** [comment]
> I read through the placeholder api wiki a bit, it seems relatively simple, especially with the way things read set up.
> 
> From my understanding placeholder api runs a set method whenever a placeholder is referenced, and whatever is returned from that is used in the placeholder (returning null makes it fail and not change the placeholder). If I’m not mistaken this plug-in handles pronouns in a similar method, using a method in it’s own api to return the pronouns of a specific player in string form. So in theory it should work.
> 
> if you want I can have a go at trying to add this, it seems simple enough to me at least. It really depends on if I get a sudden burst of motivation again like yesterday was like.
> 
> _btw here’s the [placeholder api wiki](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki)_

I'll see if I can get this plugin to softdepend on Placeholder API and stuff properly.

**Comment by EnbyAce** [comment]
@Stonewall0210 The plugin _should_ now correctly softdepend on PlaceholderAPI and integrate with it if it's found.

@Purrrpley I don't have access to the AutHelper plugin, and I've heard it's going to be rewritten as well. So except for letting other plugins get the pronouns of players and integrating with PlaceholderAPI I can't do much about it.

**Comment by EnbyAce** [comment]
Reopening this issue
